import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import federation from '@originjs/vite-plugin-federation'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react({
      babel: {
        plugins: ['babel-plugin-react-compiler'],
      },
    }),
    /**
     * Module Federation Configuration for Host (OS Shell)
     * 
     * This configuration consumes remote micro-frontend applications.
     * Each remote exposes components that can be dynamically loaded.
     * 
     * Key settings:
     * - name: Identifier for this host application
     * - remotes: Map of remote names to their entry point URLs
     * - shared: Dependencies shared with remotes to avoid duplicate instances
     */
    federation({
      name: 'host',
      remotes: {
        // Remote Calculator app - runs on port 5001 during development
        // The remoteEntry.js is generated by the remote's federation plugin
        remoteCalculator: 'http://localhost:5001/assets/remoteEntry.js',
      },
      shared: {
        // React must be shared as singleton to prevent "multiple React instances" error
        // Both host and remotes will use the same React instance
        react: {
          singleton: true,
          requiredVersion: '^19.0.0',
        },
        'react-dom': {
          singleton: true,
          requiredVersion: '^19.0.0',
        },
      },
    }),
  ],
  
  // Build configuration
  build: {
    // Required for Module Federation top-level await support
    target: 'esnext',
    modulePreload: false,
    minify: false,
    cssCodeSplit: false,
  },
})
